theme: PaperMod
languageCode: en-us
title: BoxDB
baseURL: https://bxd.vercel.app
params:
  profileMode:
    enabled: true
    title: bxd
    subtitle: Object Relational Mapping for IndexedDB
    imageUrl: /logo.png
    imageTitle: logo
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Get Started
        url: getting-started
      - name: API Reference
        url: apis
  socialIcons:
    - name: github
      url: https://github.com/leegeunhyeok/bxd
  assets:
    disableHLJS: true
  pygmentsCodeFences: true
  pygmentsUseClasses: true
  defaultTheme: auto
  editPost:
    URL: https://github.com/leegeunhyeok/bxd-docs/tree/master/content
    Text: Suggest Changes
    appendFilePath: true
menu:
  main:
    - identifier: start
      name: Get started
      url: getting-started/
      weight: 1
    - identifier: apis
      name: APIs
      url: apis/
      weight: 2
    - identifier: example
      name: Example
      url: example/
      weight: 3
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: nord
languages:
  en:
    weight: 1
    url: /
  kr:
    weight: 2
    url: /kr
