theme: PaperMod
languageCode: en-us
title: BoxDB
params:
  profileMode:
    enabled: true
    title: bxd
    subtitle: Object relational mapping for IndexedDB
    imageUrl: logo.png
    imageTitle: logo
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Get Started
        url: /getting-started
      - name: API Reference
        url: /apis
  socialIcons:
    - name: github
      url: https://github.com/leegeunhyeok/bxd
  assets:
    disableHLJS: true
  pygmentsCodeFences: true
  pygmentsUseClasses: true
menu:
  main:
    - identifier: start
      name: Get started
      url: /getting-started/
      weight: 1
    - identifier: apis
      name: APIs
      url: /apis/
      weight: 2
    - identifier: example
      name: Example
      url: /example/
      weight: 3
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: nord
